/* ==========================================================================
   AI Insights View Controller
   ========================================================================== */

import { API } from './api.js';
import { AIEngine } from './ai.js';

export const InsightsController = {
  async render() {
    const container = document.getElementById('insights-view-container');
    if (!container) return;

    const complaints = await API.getComplaints();
    const insights = AIEngine.generateInsights(complaints);

    container.innerHTML = `
      <div style="margin-bottom: 1.5rem;">
        <span style="font-size: 0.75rem; font-weight: 800; color: #38bdf8; letter-spacing: 0.05em; background: rgba(56, 189, 248, 0.15); padding: 0.25rem 0.65rem; border-radius: var(--radius-full);">
          AI PROTOTYPE ANALYSIS & AUTOMATED PREDICTIVE INSIGHTS
        </span>
        <h2 style="font-size: 1.6rem; font-weight: 800; margin-top: 0.5rem;">City-Wide AI Intelligence Briefing</h2>
        <p style="color: var(--text-secondary); font-size: 0.9rem;">
          Continuous pattern detection analyzing ${complaints.length} active civic reports across municipal zones.
        </p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 1.25rem; margin-bottom: 1.5rem;">
        <div class="card" style="border-left: 4px solid #38bdf8;">
          <div style="font-size: 0.75rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase;">HOTSPOT LOCATION DETECTED</div>
          <h3 style="font-size: 1.3rem; font-weight: 800; margin-top: 0.3rem; color: #38bdf8;">${insights.topHotspot}</h3>
          <p style="font-size: 0.82rem; color: var(--text-secondary); margin-top: 0.4rem;">
            Highest concentration of reported issues (${insights.repeatedCount} active reports in 1km radius).
          </p>
        </div>

        <div class="card" style="border-left: 4px solid #f97316;">
          <div style="font-size: 0.75rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase;">MOST RECURRING CATEGORY</div>
          <h3 style="font-size: 1.3rem; font-weight: 800; margin-top: 0.3rem; color: #f97316;">${insights.mostCommonCategory}</h3>
          <p style="font-size: 0.82rem; color: var(--text-secondary); margin-top: 0.4rem;">
            Represents the highest volume of incoming citizen complaints this month.
          </p>
        </div>
      </div>

      <!-- Repeated Issue Alert Card -->
      <div class="card" style="background: rgba(245, 158, 11, 0.1); border: 1px solid rgba(245, 158, 11, 0.3); margin-bottom: 1.5rem;">
        <div style="display: flex; align-items: flex-start; gap: 0.85rem;">
          <span style="font-size: 1.6rem; color: #f59e0b;">🔄</span>
          <div>
            <h4 style="font-size: 1.05rem; font-weight: 800; color: #fbbf24;">Repeated Issue Anomaly Flagged</h4>
            <p style="font-size: 0.88rem; color: var(--text-primary); margin-top: 0.25rem;">
              <strong>Drainage & Sewage complaints reported 14 times in the same corridor (Central Junction).</strong>
            </p>
            <p style="font-size: 0.8rem; color: var(--text-secondary); margin-top: 0.25rem;">
              AI Model recommendation: Underground pipe structural defect suspected. Routine surface flushing is ineffective. Heavy engineering intervention required.
            </p>
          </div>
        </div>
      </div>

      <!-- Strategic Priority Recommendation Card -->
      <div class="card" style="background: linear-gradient(135deg, rgba(37, 99, 235, 0.15), rgba(6, 182, 212, 0.1)); border: 1px solid #38bdf8;">
        <h3 class="card-title" style="color: #38bdf8; margin-bottom: 0.75rem;">
          <span>🎯</span> Priority Executive Recommendation
        </h3>
        <p style="font-size: 0.95rem; font-weight: 600; color: var(--text-primary); margin-bottom: 0.5rem;">
          ${insights.recommendationText}
        </p>
        <p style="font-size: 0.82rem; color: var(--text-secondary);">
          Automated dispatch recommendation generated by CivicTrack AI predictive engine based on public impact, proximity density, and SLA delay risk.
        </p>
      </div>
    `;
  }
};
